# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bfa657005c2d330f4d8c08aa258b653769a126fba5a5681d06e1be8cbb33388e566dfb51e8fa1f0c465d2cb1d1f00e5b7bad230adf3ba478a30c94c5f3f1383

test:
  secret_key_base: d740709a991d24dc376d9dd36ff9fd7f808bc8b1829ed341edf30563812dbb6f16b406ae3f52147fc06b2c279edee1a704b5f3f4b8ebea3b3f2fb3514833d1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
